import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/theme';

export const styles = StyleSheet.create({
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 18,
  },
  completeModalCard: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    maxHeight: '85%',
    elevation: 6,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 10,
  },
  completeModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  completeModalTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#234E52',
  },
  closeBtnText: {
    fontSize: 18,
    color: COLORS.muted,
    fontWeight: '700',
    padding: 4,
  },
  completeModalSub: {
    fontSize: 13,
    color: COLORS.muted,
    marginBottom: 10,
  },
  completeNoticeText: {
    fontSize: 12,
    color: COLORS.inkSoft,
    lineHeight: 17,
    marginBottom: 12,
  },
  deltaScrollList: {
    maxHeight: 250,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
    padding: 10,
    marginBottom: 16,
  },
  deltaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#EDF2F7',
  },
  deltaMatName: {
    fontSize: 12.5,
    fontWeight: '700',
    color: COLORS.ink,
  },
  deltaMatSub: {
    fontSize: 11,
    color: COLORS.muted,
    marginTop: 1,
  },
  deltaBadgeUnder: {
    backgroundColor: '#E6FFFA',
    borderWidth: 1,
    borderColor: '#38B2AC',
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  deltaBadgeUnderText: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#234E52',
  },
  deltaBadgeOver: {
    backgroundColor: '#FFF5F5',
    borderWidth: 1,
    borderColor: '#FEB2B2',
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  deltaBadgeOverText: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#9B2C2C',
  },
  deltaBadgeExact: {
    backgroundColor: '#EDF2F7',
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  deltaBadgeExactText: {
    fontSize: 10.5,
    fontWeight: '700',
    color: COLORS.muted,
  },
  completeActionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  overCancelBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#CBD5E0',
    backgroundColor: '#F7FAFC',
    alignItems: 'center',
  },
  overCancelText: {
    fontSize: 13.5,
    fontWeight: '700',
    color: COLORS.muted,
  },
  completeConfirmBtn: {
    flex: 1.6,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: '#319795',
    alignItems: 'center',
  },
  completeConfirmText: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#FFFFFF',
  },
});
