import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/theme';

export const styles = StyleSheet.create({
  bookCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: COLORS.line,
    padding: 14,
    marginBottom: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
  },
  bookCardOver: {
    borderColor: '#FEB2B2',
    backgroundColor: '#FFF5F5',
  },
  bookCardCompleted: {
    borderColor: '#B2F5EA',
    backgroundColor: '#F7FFFD',
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 12,
  },
  iconBox: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
    borderWidth: 1.5,
    borderColor: '#CBD5E1',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 2,
  },
  iconSymbol: {
    fontSize: 20,
    fontWeight: '900',
    color: COLORS.ink,
  },
  iconBoxOver: {
    backgroundColor: '#FFF5F5',
    borderColor: '#FEB2B2',
  },
  iconSymbolOver: {
    color: COLORS.red,
  },
  cardHeaderCol: {
    flex: 1,
  },
  posRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 5,
  },
  posChip: {
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  posChipText: {
    fontSize: 11,
    fontWeight: '800',
    color: COLORS.primary,
  },
  unplannedBadgeChip: {
    backgroundColor: '#FEF3C7',
    borderWidth: 1,
    borderColor: '#F59E0B',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  unplannedBadgeChipText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#B45309',
  },
  hintChip: {
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  hintChipText: {
    fontSize: 10.5,
    fontWeight: '700',
    color: COLORS.inkSoft,
  },
  overBadge: {
    backgroundColor: '#FED7D7',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 1,
    marginLeft: 4,
  },
  overBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#9B2C2C',
  },
  matName: {
    fontSize: 18,
    fontWeight: '900',
    color: COLORS.ink,
    lineHeight: 23,
    marginBottom: 3,
    letterSpacing: -0.3,
  },
  matGloss: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.muted,
  },
  matGroup: {
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.muted,
    lineHeight: 17,
  },
  metricsContainer: {
    flexDirection: 'row',
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingVertical: 8,
    paddingHorizontal: 6,
    marginBottom: 10,
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  metricCell: {
    flex: 1,
    alignItems: 'center',
  },
  metricLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: COLORS.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
    marginBottom: 2,
  },
  metricValue: {
    fontSize: 13.5,
    fontWeight: '800',
    color: COLORS.ink,
  },
  metricUnit: {
    fontSize: 10,
    fontWeight: '600',
    color: COLORS.muted,
  },
  metricSub: {
    fontSize: 9.5,
    color: COLORS.muted,
    marginTop: 1,
  },
  metricDivider: {
    width: 1,
    height: 28,
    backgroundColor: '#E2E8F0',
  },
  metricValOver: {
    color: COLORS.red,
  },
  metricValDone: {
    color: '#276749',
  },
  progressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  progressPctText: {
    fontSize: 11.5,
    fontWeight: '800',
    color: COLORS.inkSoft,
    minWidth: 42,
    textAlign: 'right',
  },
  progressPctTextOver: {
    color: COLORS.red,
  },
  cardFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 4,
  },
  reasonBadge: {
    backgroundColor: '#FEFCBF',
    borderWidth: 1,
    borderColor: '#ECC94B',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  reasonBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#744210',
  },
  overWarningText: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.red,
  },
  stepperWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: COLORS.line,
    borderRadius: 12,
    overflow: 'hidden',
  },
  stepperBtn: {
    width: 36,
    height: 42,
    backgroundColor: '#F6F8FA',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepperBtnText: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.ink,
  },
  stepperValBox: {
    minWidth: 50,
    paddingHorizontal: 6,
    alignItems: 'center',
  },
  stepperValText: {
    fontSize: 15,
    fontWeight: '800',
    color: COLORS.ink,
  },
  stepperUnitText: {
    fontSize: 8.5,
    color: COLORS.muted,
    fontWeight: '700',
    marginTop: -2,
    textAlign: 'center',
  },
});
