import { StyleSheet, Platform } from 'react-native';
import { COLORS } from '../../constants/theme';

export const styles = StyleSheet.create({
  modalFullscreen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.line,
    backgroundColor: '#FFFFFF',
  },
  modalTitleBox: {
    flex: 1,
  },
  modalMainTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.ink,
  },
  modalSubTitle: {
    fontSize: 13,
    color: COLORS.muted,
    marginTop: 2,
  },
  modalCloseBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#F1F4F7',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 12,
  },
  modalCloseIcon: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.inkSoft,
  },
  modalBody: {
    flex: 1,
    backgroundColor: '#FAFCFE',
  },
  modalScrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  modalField: {
    marginBottom: 18,
  },
  modalFieldLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: COLORS.inkSoft,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 7,
  },
  posChip: {
    backgroundColor: '#EDF2F7',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    alignSelf: 'flex-start',
  },
  posChipText: {
    fontSize: 11,
    fontWeight: '800',
    color: COLORS.inkSoft,
  },
  overNoticeBox: {
    backgroundColor: '#FEF2F2',
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#FECACA',
    padding: 16,
    marginBottom: 16,
  },
  overNoticeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  overNoticeIcon: {
    fontSize: 20,
  },
  overNoticeTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#991B1B',
    flex: 1,
  },
  overNoticeMatName: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.ink,
    marginBottom: 8,
  },
  overNoticeMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  overNoticeMetaText: {
    fontSize: 13,
    color: COLORS.muted,
  },
  overQtyControlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  overStepBtn: {
    width: 52,
    height: 52,
    borderRadius: 14,
    backgroundColor: '#EFF6FF',
    borderWidth: 1.5,
    borderColor: '#BFDBFE',
    justifyContent: 'center',
    alignItems: 'center',
  },
  overStepBtnText: {
    fontSize: 26,
    fontWeight: '800',
    color: COLORS.primary,
    lineHeight: 28,
  },
  overInputWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderWidth: 2,
    borderColor: COLORS.primary,
    borderRadius: 14,
    paddingHorizontal: 14,
    height: 52,
  },
  overInputWrapWarn: {
    borderColor: COLORS.red,
    backgroundColor: '#FEF2F2',
  },
  overPlusSign: {
    fontSize: 22,
    fontWeight: '900',
    color: COLORS.primary,
    marginRight: 6,
  },
  overQtyInput: {
    flex: 1,
    fontSize: 22,
    fontWeight: '900',
    color: COLORS.ink,
    paddingVertical: 0,
  },
  overUnitSuffix: {
    fontSize: 15,
    fontWeight: '800',
    color: COLORS.muted,
    marginLeft: 6,
  },
  overDeliveryWarnBox: {
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginTop: 8,
    marginBottom: 4,
  },
  overDeliveryWarnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#B91C1C',
  },
  overQuickLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.muted,
    marginBottom: 8,
    marginTop: 4,
  },
  overQuickPillsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  overQuickPill: {
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 20,
    paddingHorizontal: 13,
    paddingVertical: 7,
  },
  overQuickPillActive: {
    backgroundColor: '#EFF6FF',
    borderColor: COLORS.primary,
  },
  overQuickPillText: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.inkSoft,
  },
  overQuickPillTextActive: {
    color: COLORS.primary,
    fontWeight: '900',
  },
  quickPillsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  reasonPill: {
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  reasonPillActive: {
    backgroundColor: '#FEFCBF',
    borderColor: '#D69E2E',
  },
  reasonPillText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: COLORS.inkSoft,
  },
  reasonPillTextActive: {
    color: '#744210',
    fontWeight: '800',
  },
  overReasonInputFullscreen: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1.5,
    borderColor: COLORS.line,
    borderRadius: 12,
    padding: 12,
    fontSize: 14,
    color: COLORS.ink,
    minHeight: 80,
    textAlignVertical: 'top',
    marginBottom: 16,
  },
  stickyModalFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: Platform.OS === 'ios' ? 24 : 16,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    gap: 12,
  },
  overCancelBtnLarge: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: COLORS.line,
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
  },
  overCancelTextLarge: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.muted,
  },
  overConfirmBtnLarge: {
    flex: 2,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: COLORS.primary || '#2563EB',
    alignItems: 'center',
    shadowColor: COLORS.primary || '#2563EB',
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
    elevation: 3,
  },
  overConfirmBtnDisabled: {
    backgroundColor: '#E2E8F0',
    shadowOpacity: 0,
    elevation: 0,
  },
  overConfirmTextLarge: {
    fontSize: 14,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  overConfirmTextDisabled: {
    color: '#94A3B8',
  },
});
