import { StyleSheet, Platform } from 'react-native';
import { COLORS } from '../../constants/theme';

export const styles = StyleSheet.create({
  modalFullscreen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.line,
    backgroundColor: '#FFFFFF',
  },
  modalTitleBox: {
    flex: 1,
  },
  modalMainTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.ink,
  },
  modalSubTitle: {
    fontSize: 13,
    color: COLORS.muted,
    marginTop: 2,
  },
  modalCloseBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#F1F4F7',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 12,
  },
  modalCloseIcon: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.inkSoft,
  },
  modalBody: {
    flex: 1,
    backgroundColor: '#FAFCFE',
  },
  modalScrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  unclearInfoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EBF8FF',
    borderWidth: 1,
    borderColor: '#BEE3F8',
    borderRadius: 10,
    padding: 12,
    marginBottom: 16,
    gap: 10,
  },
  unclearInfoIcon: {
    fontSize: 18,
  },
  unclearInfoText: {
    flex: 1,
    fontSize: 12.5,
    color: '#2B6CB0',
    lineHeight: 18,
  },
  modalField: {
    marginBottom: 18,
  },
  modalFieldLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: COLORS.inkSoft,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 7,
  },
  requiredStar: {
    color: '#E53E3E',
    fontWeight: '900',
  },
  modalInput: {
    borderWidth: 1.5,
    borderColor: COLORS.line,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: COLORS.ink,
    backgroundColor: '#FFFFFF',
  },
  inputInvalid: {
    borderColor: '#E53E3E',
    borderWidth: 1.5,
    backgroundColor: '#FFF5F5',
  },
  unclearSuggestionsBox: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#90CDF4',
    borderRadius: 10,
    marginBottom: 10,
    maxHeight: 200,
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    overflow: 'hidden',
  },
  unclearSugHeader: {
    fontSize: 10.5,
    fontWeight: '800',
    color: COLORS.blue,
    backgroundColor: '#EBF8FF',
    paddingHorizontal: 12,
    paddingVertical: 5,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  unclearSugItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderBottomWidth: 1,
    borderBottomColor: '#EDF2F7',
    backgroundColor: '#FFFFFF',
  },
  unclearSugName: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.ink,
  },
  unclearSugMeta: {
    fontSize: 11,
    color: COLORS.muted,
    marginTop: 2,
  },
  unclearSugBadge: {
    backgroundColor: '#E6FFFA',
    borderWidth: 1,
    borderColor: '#38B2AC',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginLeft: 8,
  },
  unclearSugBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#234E52',
  },
  unitSelectorRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 10,
  },
  unitToggle: {
    flex: 1,
    borderWidth: 1.5,
    borderColor: COLORS.line,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  unitToggleActive: {
    borderColor: COLORS.amber,
    backgroundColor: COLORS.lite,
  },
  unitToggleText: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.muted,
  },
  unitToggleTextActive: {
    color: COLORS.amberDark,
    fontWeight: '800',
  },
  quickPillsRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  pill: {
    backgroundColor: '#F1F4F7',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.line,
  },
  pillActive: {
    backgroundColor: COLORS.lite,
    borderColor: COLORS.amber,
  },
  pillText: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.inkSoft,
  },
  pillTextActive: {
    color: COLORS.amberDark,
  },
  multilineInput: {
    minHeight: 84,
    textAlignVertical: 'top',
    paddingTop: 12,
    lineHeight: 20,
  },
  modalStickyFooter: {
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    paddingHorizontal: 16,
    paddingVertical: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 8,
  },
  missingHintBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EDF2F7',
    borderWidth: 1.5,
    borderColor: '#CBD5E0',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 8,
    marginBottom: 4,
    gap: 8,
  },
  missingHintIcon: {
    fontSize: 16,
  },
  missingHintTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: '#4A5568',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 2,
  },
  missingHintList: {
    fontSize: 12,
    fontWeight: '700',
    color: '#C53030',
    lineHeight: 16,
  },
  modalSubmitBtn: {
    backgroundColor: COLORS.amber,
    borderRadius: 14,
    paddingVertical: 15,
    alignItems: 'center',
    marginTop: 14,
  },
  modalSubmitText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 16,
  },
});
