// Master data fallback for Hallenbad Weingarten & Burk Haustechnik

export const DEFAULT_PROJECT_ID = 'hallenbad-weingarten';

export const DEFAULT_PROJECT = {
  id: 'hallenbad-weingarten',
  name: 'Hallenbad Weingarten Sanierung',
  projectNumber: '1638 / 24316-044',
  client: 'Stadt Weingarten',
  location: 'Weingarten',
  address: 'Brechenmacherstraße 11, 88250 Weingarten',
  trade: 'Sanitärinstallation',
  projectManager: 'Florian Buck',
  calendarWeek: 27,
  totalDeliveredPercentage: 42,
};

export const INITIAL_ROOMS = [
  {
    id: 'room_ug_101',
    code: 'UG-101',
    name: 'WC-Bereich UG',
    sub: 'Geberit-Elemente, Abwasser',
    floor: 'UG',
    pct: 82,
    translations: { ro: 'Zonă WC (Subsol)', pl: 'Strefa WC (Piwnica)', hr: 'WC zona (Podrum)' },
    defaultMaterialIds: ['m1', 'm2', 'm4', 'm5', 'm7', 'm18', 'm43'],
  },
  {
    id: 'room_ug_102',
    code: 'UG-102',
    name: 'Technikraum UG',
    sub: 'Grauwasser-Hebeanlage, Verteiler',
    floor: 'UG',
    pct: 63,
    translations: { ro: 'Cameră tehnică (Subsol)', pl: 'Pom. techniczne (Piwnica)', hr: 'Tehnička prostorija (Podrum)' },
    defaultMaterialIds: ['m1', 'm2', 'm23', 'm24', 'm36', 'm37', 'm42', 'm47', 'm48'],
  },
  {
    id: 'room_ug_103',
    code: 'UG-103',
    name: 'Flur UG',
    sub: 'Sammelleitungen Trinkwasser',
    floor: 'UG',
    pct: 71,
    translations: { ro: 'Hol (Subsol)', pl: 'Korytarz (Piwnica)', hr: 'Hodnik (Podrum)' },
    defaultMaterialIds: ['m2', 'm3', 'm4', 'm43', 'm44', 'm45', 'm66', 'm67', 'm68'],
  },
  {
    id: 'room_ug_104',
    code: 'UG-104',
    name: 'Duschen UG',
    sub: 'Abwasser, Trinkwasser-Ringleitung',
    floor: 'UG',
    pct: 38,
    translations: { ro: 'Dușuri (Subsol)', pl: 'Prysznice (Piwnica)', hr: 'Tuševi (Podrum)' },
    defaultMaterialIds: ['m2', 'm3', 'm7', 'm11', 'm14', 'm18', 'm43', 'm66', 'm67'],
  },
  {
    id: 'room_ug_105',
    code: 'UG-105',
    name: 'Steigschacht A',
    sub: 'Steigleitungen EG / OG',
    floor: 'UG',
    pct: 20,
    translations: { ro: 'Ghenă A (Coloane)', pl: 'Szacht A (Piony)', hr: 'Vertikalni kanal A' },
    defaultMaterialIds: ['m1', 'm2', 'm8', 'm12', 'm18', 'm42', 'm68', 'm70', 'm72'],
  },
];

export const INITIAL_MATERIALS = [
  {
    id: 'm1',
    pos: '1.001',
    name: 'Schmutzwasserleitung DN 125 hochschalldämmend',
    cleanName: 'Schmutzwasserleitung DN 125 hochschalldämmend',
    group: 'Schmutzwasser (Polo Kal NG)',
    qu: 'm',
    icon: 'pipe',
    deliveredQty: 6.0,
    installedQty: 0.0,
    unitPrice: 47.38,
    isCutMaterial: true,
    containsHint: '',
  },
  {
    id: 'm2',
    pos: '1.002',
    name: 'Kunststoffrohr DN 100',
    cleanName: 'Kunststoffrohr DN 100',
    group: 'Schmutzwasser (Polo Kal NG)',
    qu: 'm',
    icon: 'pipe',
    deliveredQty: 87.25,
    installedQty: 73.75,
    unitPrice: 38.02,
    isCutMaterial: true,
    containsHint: '',
  },
  {
    id: 'm3',
    pos: '1.003',
    name: 'Kunststoffrohr DN 70',
    cleanName: 'Kunststoffrohr DN 70',
    group: 'Schmutzwasser (Polo Kal NG)',
    qu: 'm',
    icon: 'pipe',
    deliveredQty: 18.5,
    installedQty: 10.0,
    unitPrice: 30.92,
    isCutMaterial: true,
    containsHint: '',
  },
  {
    id: 'm4',
    pos: '1.004',
    name: 'Kunststoffrohr DN 50',
    cleanName: 'Kunststoffrohr DN 50',
    group: 'Schmutzwasser (Polo Kal NG)',
    qu: 'm',
    icon: 'pipe',
    deliveredQty: 45.0,
    installedQty: 20.0,
    unitPrice: 22.39,
    isCutMaterial: true,
    containsHint: '',
  },
  {
    id: 'm5',
    pos: '1.005',
    name: 'Bogen DN 50, 15° - 87°',
    cleanName: 'Bogen DN 50, 15° - 87°',
    group: 'Schmutzwasser (Polo Kal NG)',
    qu: 'Stk',
    icon: 'bend',
    deliveredQty: 110.0,
    installedQty: 31.0,
    unitPrice: 11.64,
    isCutMaterial: false,
    containsHint: '',
  },
  {
    id: 'm6',
    pos: '1.006',
    name: 'Bogen DN 70, 15° - 87°',
    cleanName: 'Bogen DN 70, 15° - 87°',
    group: 'Schmutzwasser (Polo Kal NG)',
    qu: 'Stk',
    icon: 'bend',
    deliveredQty: 70.0,
    installedQty: 14.0,
    unitPrice: 15.8,
    isCutMaterial: false,
    containsHint: '',
  },
  {
    id: 'm7',
    pos: '1.007',
    name: 'Bogen DN 100, 15° - 87°',
    cleanName: 'Bogen DN 100, 15° - 87°',
    group: 'Schmutzwasser (Polo Kal NG)',
    qu: 'Stk',
    icon: 'bend',
    deliveredQty: 109.0,
    installedQty: 92.0,
    unitPrice: 19.49,
    isCutMaterial: false,
    containsHint: '2x Enddeckel 100, 4x Steckmuffe 100',
  },
  {
    id: 'm8',
    pos: '1.008',
    name: 'Bogen DN 125, 15° - 87°',
    cleanName: 'Bogen DN 125, 15° - 87°',
    group: 'Schmutzwasser (Polo Kal NG)',
    qu: 'Stk',
    icon: 'bend',
    deliveredQty: 2.0,
    installedQty: 0.0,
    unitPrice: 34.6,
    isCutMaterial: false,
    containsHint: '',
  },
  {
    id: 'm11',
    pos: '1.011',
    name: 'Abzweig DN 100 / 100 45°',
    cleanName: 'Abzweig DN 100',
    group: 'Schmutzwasser (Polo Kal NG)',
    qu: 'Stk',
    icon: 'tee',
    deliveredQty: 46.0,
    installedQty: 34.0,
    unitPrice: 28.83,
    isCutMaterial: false,
    containsHint: '',
  },
  {
    id: 'm14',
    pos: '1.014',
    name: 'Reduzierung DN 100 / 70-50',
    cleanName: 'Reduzierung DN 100 / 70-50',
    group: 'Schmutzwasser (Polo Kal NG)',
    qu: 'Stk',
    icon: 'red',
    deliveredQty: 18.0,
    installedQty: 8.0,
    unitPrice: 20.51,
    isCutMaterial: false,
    containsHint: '',
  },
  {
    id: 'm18',
    pos: '1.018',
    name: 'Brandschutzmanschette DN 100',
    cleanName: 'Brandschutzmanschette DN 100',
    group: 'Schmutzwasser (Polo Kal NG)',
    qu: 'Stk',
    icon: 'pipe',
    deliveredQty: 8.0,
    installedQty: 0.0,
    unitPrice: 164.98,
    isCutMaterial: false,
    containsHint: '',
  },
  {
    id: 'm23',
    pos: '1.023',
    name: 'Druckrohr schwarz 50x4,6mm',
    cleanName: 'Druckrohr schwarz 50x4,6mm',
    group: 'Druckleitung Hebeanlage (Aduxa RC)',
    qu: 'm',
    icon: 'pipe',
    deliveredQty: 10.0,
    installedQty: 0.0,
    unitPrice: 11.21,
    isCutMaterial: true,
    containsHint: '',
  },
  {
    id: 'm24',
    pos: '1.024',
    name: 'HD-PE-Bogen da:50mm 15-90°',
    cleanName: 'HD-PE-Bogen da:50mm',
    group: 'Druckleitung Hebeanlage (Aduxa RC)',
    qu: 'Stk',
    icon: 'bend',
    deliveredQty: 12.0,
    installedQty: 0.0,
    unitPrice: 49.34,
    isCutMaterial: false,
    containsHint: '',
  },
  {
    id: 'm36',
    pos: '1.036',
    name: 'Schmutzwassersammelbehälter 270L Doppelhebeanlage',
    cleanName: 'Schmutzwassersammelbehälter 270L',
    group: 'Grauwasser Hebeanlage',
    qu: 'Stk',
    icon: 'pipe',
    deliveredQty: 1.0,
    installedQty: 1.0,
    unitPrice: 2308.56,
    isCutMaterial: false,
    containsHint: '',
  },
  {
    id: 'm37',
    pos: '1.037',
    name: 'Vertikale 1-stufige Schmutzwasserpumpe IP68',
    cleanName: 'Schmutzwasserpumpe IP68',
    group: 'Grauwasser Hebeanlage',
    qu: 'Stk',
    icon: 'pipe',
    deliveredQty: 2.0,
    installedQty: 2.0,
    unitPrice: 508.24,
    isCutMaterial: false,
    containsHint: '',
  },
  {
    id: 'm42',
    pos: '1.042',
    name: 'Rohrschelle NW DN 125 schallgedämmt',
    cleanName: 'Rohrschelle NW DN 125',
    group: 'Rohrbefestigung',
    qu: 'Stk',
    icon: 'clamp',
    deliveredQty: 10.0,
    installedQty: 0.0,
    unitPrice: 17.14,
    isCutMaterial: false,
    containsHint: '',
  },
  {
    id: 'm43',
    pos: '1.043',
    name: 'Rohrschelle DN 100 schallgedämmt',
    cleanName: 'Rohrschelle DN 100',
    group: 'Rohrbefestigung',
    qu: 'Stk',
    icon: 'clamp',
    deliveredQty: 100.0,
    installedQty: 76.0,
    unitPrice: 12.99,
    isCutMaterial: false,
    containsHint: '',
  },
  {
    id: 'm44',
    pos: '1.044',
    name: 'Rohrschelle DN 70 schallgedämmt',
    cleanName: 'Rohrschelle DN 70',
    group: 'Rohrbefestigung',
    qu: 'Stk',
    icon: 'clamp',
    deliveredQty: 50.0,
    installedQty: 15.0,
    unitPrice: 12.2,
    isCutMaterial: false,
    containsHint: '',
  },
  {
    id: 'm45',
    pos: '1.045',
    name: 'Rohrschelle DN 50 schallgedämmt',
    cleanName: 'Rohrschelle DN 50',
    group: 'Rohrbefestigung',
    qu: 'Stk',
    icon: 'clamp',
    deliveredQty: 50.0,
    installedQty: 30.0,
    unitPrice: 11.75,
    isCutMaterial: false,
    containsHint: '',
  },
  {
    id: 'm47',
    pos: '2.001',
    name: 'Freistrom-Absperrventil DN 15 mit Entleerung',
    cleanName: 'Freistrom-Absperrventil DN 15',
    group: 'Armaturen & Ventile',
    qu: 'Stk',
    icon: 'valve',
    deliveredQty: 2.0,
    installedQty: 2.0,
    unitPrice: 204.16,
    isCutMaterial: false,
    containsHint: '',
  },
  {
    id: 'm48',
    pos: '2.002',
    name: 'Freistrom-Absperrventil DN 20',
    cleanName: 'Freistrom-Absperrventil DN 20',
    group: 'Armaturen & Ventile',
    qu: 'Stk',
    icon: 'valve',
    deliveredQty: 3.0,
    installedQty: 3.0,
    unitPrice: 235.14,
    isCutMaterial: false,
    containsHint: '',
  },
  {
    id: 'm66',
    pos: '2.020',
    name: 'Edelstahl-System-Rohr 18 x 1,0 mm (DN 15)',
    cleanName: 'Edelstahl-Rohr 18 x 1,0 mm',
    group: 'Mapress Edelstahl Trinkwasser',
    qu: 'm',
    icon: 'pipe',
    deliveredQty: 66.0,
    installedQty: 52.0,
    unitPrice: 18.74,
    isCutMaterial: true,
    containsHint: '',
  },
  {
    id: 'm67',
    pos: '2.021',
    name: 'Edelstahl-System-Rohr 22 x 1,2 mm (DN 20)',
    cleanName: 'Edelstahl-Rohr 22 x 1,2 mm',
    group: 'Mapress Edelstahl Trinkwasser',
    qu: 'm',
    icon: 'pipe',
    deliveredQty: 72.0,
    installedQty: 25.0,
    unitPrice: 23.35,
    isCutMaterial: true,
    containsHint: '',
  },
  {
    id: 'm68',
    pos: '2.022',
    name: 'Edelstahl-System-Rohr 28 x 1,2 mm (DN 25)',
    cleanName: 'Edelstahl-Rohr 28 x 1,2 mm',
    group: 'Mapress Edelstahl Trinkwasser',
    qu: 'm',
    icon: 'pipe',
    deliveredQty: 84.0,
    installedQty: 55.0,
    unitPrice: 27.85,
    isCutMaterial: true,
    containsHint: '',
  },
  {
    id: 'm70',
    pos: '2.024',
    name: 'Edelstahl-System-Rohr 42 x 1,5 mm (DN 40)',
    cleanName: 'Edelstahl-Rohr 42 x 1,5 mm',
    group: 'Mapress Edelstahl Trinkwasser',
    qu: 'm',
    icon: 'pipe',
    deliveredQty: 42.0,
    installedQty: 18.0,
    unitPrice: 44.29,
    isCutMaterial: true,
    containsHint: '',
  },
  {
    id: 'm72',
    pos: '2.026',
    name: 'Edelstahl-System-Rohr 89 x 2,0 mm (DN 80)',
    cleanName: 'Edelstahl-Rohr 89 x 2,0 mm',
    group: 'Mapress Edelstahl Trinkwasser',
    qu: 'm',
    icon: 'pipe',
    deliveredQty: 22.0,
    installedQty: 0.0,
    unitPrice: 109.96,
    isCutMaterial: true,
    containsHint: '',
  },
];
